controller_server:
  ros__parameters:
    use_sim_time: False
    controller_frequency: 15.0 # 제어 주기 원래값: 10.0
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.001
    min_theta_velocity_threshold: 0.001
    failure_tolerance: 0.3

    progress_checker_plugin: "progress_checker"
    goal_checker_plugins: ["general_goal_checker"] 
    controller_plugins: ["FollowPath"]

    # Progress checker parameters
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.5
      movement_time_allowance: 10.0

    general_goal_checker:
      stateful: True
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.01 # 0.25
      yaw_goal_tolerance: 0.25 # 0.25
    # DWB parameters
    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      debug_trajectory_details: True
      min_vel_x: 0.0 # 후진 금지 설정 (원래값: -0.4)
      min_vel_y: 0.0
      max_vel_x: 1.0 # 속도 제한 (원래값: 0.4)
      max_vel_y: 0.0
      max_vel_theta: 1.0
      min_speed_xy: 0.0
      max_speed_xy: 1.0 # 속도 제한 (원래값: 0.4)
      min_speed_theta: 0.0
      acc_lim_x: 2.5 # 가속 제한
      acc_lim_y: 0.0
      acc_lim_theta: 3.2
      decel_lim_x: -2.5 # 감속 제한
      decel_lim_y: 0.0
      decel_lim_theta: -3.2
      vx_samples: 25
      vy_samples: 5
      vtheta_samples: 25
      sim_time: 1.2 # 예측 시간 원래값: 1.7
      linear_granularity: 0.05
      angular_granularity: 0.025    
      transform_tolerance: 0.2
      xy_goal_tolerance: 0.01 # 0.25
      trans_stopped_velocity: 0.25
      short_circuit_trajectory_evaluation: True
      stateful: True
      critics: ["RotateToGoal", "Oscillation", "BaseObstacle", "GoalAlign", "PathAlign", "PathDist", "GoalDist", "OmegaDirectionCritic"]
      OmegaDirectionCritic:
        scale: 24.0
        sector_count: 72
        omega_topic: "/future_bias/omega_weights"
      BaseObstacle.scale: 0.03
      PathAlign.scale: 32.0
      PathAlign.forward_point_distance: 0.1
      GoalAlign.scale: 24.0
      GoalAlign.forward_point_distance: 0.1
      PathDist.scale: 24.0
      GoalDist.scale: 16.0
      RotateToGoal.scale: 32.0
      RotateToGoal.slowing_factor: 5.0
      RotateToGoal.lookahead_time: -1.0
controller_server_rclcpp_node:
  ros__parameters:
    use_sim_time: False
