a:
- 1.1365177631378174
- -0.3685998320579529
- 0.005318641662597656
b:
- 0.5664306879043579
- 0.5785835981369019
- 0.004839897155761719
c:
- 1.4536082744598389
- 0.6147482395172119
- 0.005725860595703125
d:
- -0.010129928588867188
- -0.5897136926651001
- 0.0038576126098632812
initial_pos:
- -1.86
- -0.666
- 0.012
test:
- -0.042335547506809235
- -0.6704266667366028
- 0.005166053771972656
test2:
- -0.3152315616607666
- -0.41791754961013794
- 0.00220489501953125
toilet:
- -0.319
- 0.261
- 0.07
"\uC811\uC218\uCC98":
- 1.7135405540466309
- -0.6342424154281616
- 0.0020465850830078125
"\uCC44\uD608\uC2E4":
- -1.2038761377334595
- 0.6865395307540894
- -0.000347137451171875
"\uD654\uC7A5\uC2E4":
- 0.7422862648963928
- 0.21684792637825012
- 0.00498199462890625
"\uDCE3\uDC85test":
- 1.1411277055740356
- 0.16774201393127441
- 0.005373954772949219
"\uDCEC\uDC88\uC751\uAE09\uC2E4":
- 1.7044248580932617
- 0.6881111860275269
- 0.0030736923217773438
