emergency_room:
  - 5.156146049499512
  - -1.442457914352417
  - 0.0063018798828125

x_ray_room:
  - 5.038478851318359
  - -0.1811506748199463
  - 0.006302833557128906

reception:
  - 2.405634641647339
  - -0.9008545875549316
  - 0.2036153793334960938

pharmacy:
  - 2.4448399543762207
  - -0.030467987060546875
  - 0.2037336349487304688

blood_draw_room:
  - 1.3726125955581665
  - -1.7006937265396118
  - 0.008471488952636719

restroom:
  - 4.327326774597168
  - -1.7713266277313232
  - 0.005383491516113281