" \uC751\uAE09\uC2E4":
- 5.156146049499512
- -1.442457914352417
- 0.0063018798828125
"X-ray\uC2E4":
- 5.038478851318359
- -0.1811506748199463
- 0.006302833557128906
"\uC218\uB0A9":
- 2.405634641647339
- -0.9008545875549316
- 0.0036153793334960938
"\uC57D\uAD6D":
- 2.4448399543762207
- -0.030467987060546875
- 0.0037336349487304688
"\uCC44\uD608\uC2E4":
- 1.3726125955581665
- -1.7006937265396118
- 0.008471488952636719
"\uD654\uC7A5\uC2E4":
- 4.327326774597168
- -2.4313266277313232
- 0.005383491516113281
