initial_pos:
- -1.86
- -0.666
- 0.012
start:
- 0.0
- 0.0
- 0.0
test:
- 3.9865760803222656
- -0.08354967832565308
- 0.005154609680175781
xray:
- 5.038478851318359
- -0.1811506748199463
- 0.006302833557128906
